export const SET_FLIGHTS = "SET_FLIGHTS";

export const SET_SELECTED_REGION = "SET_SELECTED_REGION";
export const SET_REGION_DATA = "SET_REGION_DATA";

export const SET_FLIGHTS_DATA = "SET_FLIGHTS_DATA";

export const SET_PROCEDURE = "SET_PROCEDURE";

export const SET_SELECTED_COUNTRY = "SET_SELECTED_COUNTRY";
export const SET_DATA_COUNTRIES = "SET_DATA_COUNTRIES";

export const SET_REGION_PRICING = "SET_REGION_PRICING";
